# Todo

version: "3"

services:
    backend:
      container_name: backend
      build: backend

    client:
      container_name: client
      build: client

    telegram_bot:
      container_name: telegram_bot
      build: telegram_bot
