version: "3"

services:

    # --- --- --- --- --- ---
    backend:
      container_name: pizza-backend
      build: ./backend
      restart: always
      ports:
        - "${BACKEND_PORT}:3000"
      environment:
        - PORT=3000
        - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
      depends_on:
        - db
      networks:
        - deployment-network

    # --- --- --- --- --- ---
    db:
      container_name: pizza-db
      image: postgres:15-alpine
      restart: always
      ports:
        - "${DB_PORT}:5432"
      environment:
        - POSTGRES_PASSWORD=${PG_PASSWORD}
        - POSTGRES_USER=${PG_USER}
        - POSTGRES_DB=${PG_DB}
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - deployment-network

    # --- --- --- --- --- ---
    frontend:
      container_name: pizza-frontend
      build: ./frontend
      restart: always
      ports:
        - "${FRONTEND_PORT}:3000"
      environment:
        - PORT=3000
        - NODE_ENV=production
        - APP_URL=${FRONTEND_URL}
        - API_URL=${BACKEND_URL}
      depends_on:
        - backend

volumes:
  pgdata:

networks:
  deployment-network:
    driver: bridge