version: "3"

volumes:
    pgdata:

services:

    # --- --- --- --- --- ---
    frontend:
      container_name: pizza-frontend
      build:
        context: ./frontend
        dockerfile: DockerFileFrontend
      restart: always
      ports:
        - "${FRONTEND_PORT}:3000"
      environment:
        - PORT=3000
        - NODE_ENV=production
        - API_URL=${FRONTEND_URL}
        - API_URL=${BACKEND_URL}
      depends_on:
        - backend

    # --- --- --- --- --- ---
    backend:
      container_name: pizza-backend
      build:
        context: ./backend
        dockerfile: DockerFileBackend
      restart: always
      ports:
        - "${BACKEND_PORT}:3000"
      environment:
        - PORT=3000
        - DATABASE_URL=${POSTGRES_URL}

        - YOOKASSA_URL=${YOOKASSA_URL}
        - YOOKASSA_CALLBACK_URL=${YOOKASSA_CALLBACK_URL}
        - YOOKASSA_STORE_ID=${YOOKASSA_STORE_ID}
        - YOOKASSA_API_KEY=${YOOKASSA_API_KEY}

        - RESEND_KEY=${RESEND_KEY}
        - JWT_SECRET=${JWT_SECRET}
        - JWY_EXPIRE=${JWY_EXPIRE}
      depends_on:
        - db

    # --- --- --- --- --- ---
    db:
      container_name: pizza-db
      image: postgres:15-alpine
      restart: always
      ports:
        - "${DB_PORT}:5432"
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - pgdata:/var/lib/postgresql/data

    # --- --- --- --- --- ---
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      build: ./nginx
      restart: always
      ports:
        - "${NGINX_PORT}:80"
      environment:
        - NGINX_PORT=${NGINX_PORT}
        - NGINX_HOST=${APP_HOST}
        - FRONTEND_URL=http://frontend:${FRONTEND_PORT}
        - BACKEND_URL=http://frontend:${BACKEND_PORT}
      depends_on:
        - frontend
        - backend